### ISSUE TITLE
classifypixelsunet error: Model has moved from Google Drive

### ISSUE THREAD

**Issue by r0f1** [CellProfiler/CellProfiler-plugins#121] opened 2021-04-20 19:53 UTC
Hi, I am trying to find the trained model weights, but they seemed to have been moved/deleted in Google Drive.
If am refering to these lines: https://github.com/CellProfiler/CellProfiler-plugins/blob/0a63e2dc71dc6a99b6112c3be70f8c2dc9301d2a/CellProfiler4_AutoConvert/classifypixelsunet.py#L149-L151

Any idea how to get them back?

**Comment by bethac07** [comment] 2021-04-20 21:38
Thanks, we can reproduce and are working on it.

**Comment by ErinWeisbart** [comment] 2023-05-09 19:56
I am closing this issue because it refers to a plugin that we are not currently maintaining.

**Closed by ErinWeisbart** 2023-05-09 19:56 UTC
