### ISSUE TITLE
Active contour model unpack error

### ISSUE THREAD

**Issue by ge2sasag** [CellProfiler/CellProfiler-plugins#69] opened 2018-08-01 09:46 UTC
Hi,

I'm trying to use Active contour model in Cellprofiler version 3.1.5 but I get this error:

Error while processing Active contour model: need more than 2 values to unpack.

How can I solve it?

Thank you in advance
Gema

**Comment by AetherUnbound** [comment] 2018-09-18 15:30
Hi @ge2sasag! Are you using the compiled version of CellProfiler by chance? What settings are you using for active contours? And if possible, can you provide a minimal image set/pipeline to reproduce the error?

**Comment by ErinWeisbart** [comment] 2023-05-09 19:47
I am closing this issue because it refers to a plugin that we are not currently maintaining.

**Closed by ErinWeisbart** 2023-05-09 19:47 UTC
Labels: needs verification
